### ISSUE TITLE
Questions about how to run the training process?

### ISSUE THREAD

**Issue by lircsszz** [IIT-PAVIS/Acoustic-Image-Generation#1]
Hi, I read your paper and it was very exciting and inspiring. I hope you can provide some training details, such as how the dataset is placed(e.g. training.txt), and the related download address. Being able to run through your code would be a great help to subsequent researchers.

**Comment by ValentinaSanguineti** [comment]
Thank you for your appreciation. For the dataset, send me an email with the purpose of your research and I will provide the link. 
The .txt are in another repository https://github.com/IIT-PAVIS/acoustic-images-self-supervision/tree/master/lists which has been created for the paper presenting the dataset. Write to my email valentina.sanguineti@fastwebnet.it for any other information.

**Comment by lircsszz** [comment]
> Thank you for your appreciation. For the dataset, send me an email with the purpose of your research and I will provide the link. The .txt are in another repository https://github.com/IIT-PAVIS/acoustic-images-self-supervision/tree/master/lists which has been created for the paper presenting the dataset. Write to my email [valentina.sanguineti@fastwebnet.it](mailto:valentina.sanguineti@fastwebnet.it) for any other information.

Thanks for the kindly reply, I've figured out how to run the training, thanks again!
