### ISSUE TITLE
question about convert_data3.py

### ISSUE THREAD

**Issue by lircsszz** [IIT-PAVIS/Acoustic-Image-Generation#2]
Hi, I run into a problem in convert_data3.py, does the "'''Create tfrecords for AVE'''" mean ECCV2018 paper "Audio-Visual Event Localization in Unconstrained Videos"? If so, the AVE dataset do not have '{}/*/*/video/ this kind of path, and it also dont have 'class_.*' kind file.

**Comment by ValentinaSanguineti** [comment]
Yes, AVE is the dataset proposed by that work and used by See the Sound, Hear the Pixels, which also created a sound heatmap. The instructions to download AVE are in https://github.com/YapengTian/AVE-ECCV18. In AVE, if you check annotations.txt and convert in csv format, you can obtain classes and same folders and paths using the script file https://github.com/IIT-PAVIS/Acoustic-Image-Generation/blob/main/readave.py.

**Comment by lircsszz** [comment]
Thanks alot!
